AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 instance automation for our development enviroment"
Metadata: {}

Parameters: {} 

Mappings: {}

Conditions: {} 

Resources:
 DevWebserver:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: linus-demo-n-virginia
    ImageId: ami-053b0d53c279acc90
    InstanceType: t2.micro
    Monitoring: true
    SecurityGroupIds:
      - sg-038877db3e094f831
    UserData: !Base64 |
      #!/bin/bash 
      sudo su
      apt update -y
      apt -y install apache2
      systemctl start apache2
      systemctl enable apache2
      apt install wget -y
      wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip  
      apt install unzip -y
      unzip jjtech-streaming-application-v1.zip
      rm -f /var/www/html/index.html
      cp -rf jjtech-streaming-application-v1/* /var/www/html/
      
    Tags:
      - Key: Name
        Value: DevWebserver



